name: Testing (PR)
on:
  pull_request
jobs:
  testing-build:
    name: ${{ matrix.command }}
    strategy:
      # Don't cancel all jobs just because one fails.
      fail-fast: false
      matrix:
        command: [npm run build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run ${{ matrix.command }}
        run: ${{ matrix.command }}
